### ISSUE TITLE
Issue with Compressor + String to Expression

### ISSUE THREAD

**Issue by iwarp** [zeusssz/hercules-obfuscator#21]
with string to expression, it can generate a negative number for example
`string.char(102 - -15)`

with the compressor flag enabled it removes the spaces, and it turn it into a comment for the rest of the line

`string.char(102--15)`

![image](https://github.com/user-attachments/assets/395d62ae-1352-406a-befb-04fc7806ad25)

Thanks for the quick turn around on all these issues

**Comment by zeusssz** [comment]
fixing soon

**Comment by zeusssz** [comment]
@iwarp sent out a patch, test if it works in this case

**Comment by iwarp** [comment]
Yup that fixed this issue @zeusssz
