### ISSUE TITLE
lua: hercules.lua:170: '=' expected near 'print'

### ISSUE THREAD

**Issue by playvoras** [zeusssz/hercules-obfuscator#22]
eeeeeeeeee

**Comment by playvoras** [comment]
local function usage() end simple fix lol

**Comment by zeusssz** [comment]
elaborate?

**Comment by GofrHD** [comment]
> local function usage() end simple fix lol

where should i put it??

**Comment by 9poole** [comment]
40 blank lines between 2 functions

**Comment by zeusssz** [comment]
@playvoras elaborate??

**Comment by playvoras** [comment]
@zeusssz tf is elaborate?

**Comment by zeusssz** [comment]
what even is the issue

**Comment by playvoras** [comment]
the title

**Comment by zeusssz** [comment]
fixed
