### ISSUE TITLE
Issue with variable_renamer

### ISSUE THREAD

**Issue by iwarp** [zeusssz/hercules-obfuscator#24]
When you define a variable and that is initialized later causes the obfuscation to rename local.

**Input Code**
```
local function Broken()
    local line
    local line2 = ""

    -- define line later
    line = "abc"
end
```

**Output Code**
```
SYZkCAgNT function NESlvYgbz()
	SYZkCAgNT NmneaJFcDX
    SYZkCAgNT ZfRFLJMVHvv = ""

    -- define NmneaJFcDX later
    NmneaJFcDX = "abc"
    ZfRFLJMVHvv = "abc"
end
```

**Comment by zeusssz** [comment]
local is in the protected list for the renamer. that should not be happening. ill see what is causing this

**Comment by zeusssz** [comment]
this should have been fixed now

**Comment by iwarp** [comment]
Just tested this again

Looks like it's now encoding the function and the locals string on the output

```
local UGOieGYSmHXN ypVXCGByN()
    tdTkFxkNhYn BHrTZnNae
    tdTkFxkNhYn tBvBjNJDE = ""

    -- define BHrTZnNae later
    BHrTZnNae = "abc"
    tBvBjNJDE = "abc"
end
```
