### ISSUE TITLE
Issue with variable_renabler Global Functions

### ISSUE THREAD

**Issue by iwarp** [zeusssz/hercules-obfuscator#25]
This may be more of a question, should the obfuscator be renaming the returns from the global functions when the name matches? The functions are external method that are not in this file i'm obfuscating.

**Input Code**
```
local function Create()
end

local function Test()
    GlobalFunction().Create()
    GlobalFunction().Prop:Create()
end
```

**Output Code**
```
local function ASCAAIqh()
end

local function XSEcXnYsJn()
    GlobalFunction().ASCAAIqh()
    GlobalFunction().Prop:ASCAAIqh()
end
```

**Comment by zeusssz** [comment]
not intended behaviour at all. it should output something akin to
```lua
local function ASCAAIqh()
end

local function XSEcXnYsJn()
    XHRFlkrK().ASCAAIqh()
    XHRFlkrK().Prop:ASCAAIqh()
end
```

**Comment by iwarp** [comment]
I'm just testing the variable renamer only all features others disabled. --VR

The GlobalFunction() comes from outside of my project from the product I'm scripting against. There is no require statement, I'm unable to provide the module details other than some sample code

```
	local seq = DataPool().Sequences[target]
	local macro = DataPool().Macros[target]
	local tc = DataPool().Timecodes[target]

	local cue = DataPool().Sequences:Insert(3)
```

**Comment by zeusssz** [comment]
indeed it should. looking into it
