### ISSUE TITLE
Variable renaming + virtual machine doesnt work

### ISSUE THREAD

**Issue by RaoufiTech** [zeusssz/hercules-obfuscator#29]
As the title says, enabling both of the features gives errors.

lua: ...reter/LuaInterpreter/Parser/SyntaxParsers/Statements.lua:179: attempt to index a nil value (local 'functionCall')
stack traceback:
    ...reter/LuaInterpreter/Parser/SyntaxParsers/Statements.lua:179: in function 'Interpreter/LuaInterpreter/Parser/SyntaxParsers/Statements.consumeMethodCall'
    (...tail calls...)
    ...er/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.lua:214: in function 'Interpreter/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.parsePrefixExpression'
    (...tail calls...)
    ...er/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.lua:242: in function 'Interpreter/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.parseBinaryExpression'
    ...er/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.lua:62: in function 'Interpreter/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.getExpression'
    ...er/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.lua:77: in function 'Interpreter/LuaInterpreter/Parser/LuaMathParser/LuaMathParser.getExpressions'
    ...reter/LuaInterpreter/Parser/SyntaxParsers/Statements.lua:38: in function 'Interpreter/LuaInterpreter/Parser/SyntaxParsers/Statements.consumeVariableAssignment'
    (...tail calls...)
    ...../Compiler/Interpreter/LuaInterpreter/Parser/Parser.lua:140: in method 'getNextNode'
    ...../Compiler/Interpreter/LuaInterpreter/Parser/Parser.lua:151: in method 'consumeCodeBlock'
    ...../Compiler/Interpreter/LuaInterpreter/Parser/Parser.lua:188: in method 'parse'
    .\modules/Compiler/../Compiler/api.lua:59: in field 'ConvertToAST'
    .\modules/Compiler/../Compiler/api.lua:159: in function <.\modules/Compiler/../Compiler/api.lua:156>
    (...tail calls...)
    .\pipeline.lua:58: in function 'pipeline.process'
    hercules.lua:294: in main chunk
    [C]: in ?

**Comment by zeusssz** [comment]
what operating system are you using?
are you using lua5.4?

**Comment by RaoufiTech** [comment]
Hi
I am using Windows 11 24H2 and yes I am using Lua 5.4.

**Comment by RaoufiTech** [comment]
The obfuscator doesn't really work for LuaU. How can we add Luau support?

**Comment by zeusssz** [comment]
yeah, aware of the luau thing. this obfuscator is built from the ground up on lua5.4, and luau is 5.1 based. major changes for luau support, sadly

**Comment by RaoufiTech** [comment]
Would it be possible to update it or add support for LuaU 5.1? I am not sure what scripts to change and for what LuaU version is the compiler?
What is standalone Lua even used for lol.

**Comment by zeusssz** [comment]
we will be doing so. soon
