### ISSUE TITLE
suggestion roblox luac compadiblity

### ISSUE THREAD

**Issue by nekohacker591** [zeusssz/hercules-obfuscator#7]
due to roblox complience it also cant use these functions:

Obscuring engine features within scripts, including LuaVMs, [getfenv()](https://create.roblox.com/docs/reference/engine/globals/LuaGlobals#getfenv), and [setfenv()](https://create.roblox.com/docs/reference/engine/globals/LuaGlobals#setfenv).
Requiring remote assets, including [require(assetId)](https://create.roblox.com/docs/reference/engine/globals/RobloxGlobals#require), [loadstring()](https://create.roblox.com/docs/reference/engine/globals/LuaGlobals#loadstring), [InsertService:LoadAsset()](https://create.roblox.com/docs/reference/engine/classes/InsertService#LoadAsset), and [ModuleScript.LinkedSource](https://create.roblox.com/docs/reference/engine/classes/ModuleScript#LinkedSource). Assets that may look useful on the surface could load another "virus" asset at runtime.

they also ban obfuscation but their detection is dogshit its just that they delete any script using the functions i list here

**Comment by zeusssz** [comment]
could you elaborate on this idea? it would help us understand what you want more accurately

**Comment by nekohacker591** [comment]
basicly alot of obfuscations use getfenv ir another engine obscuring functions im basicly just asking if you can make focuas develpment on not having the functions i listed in hyperlink blue

**Comment by zeusssz** [comment]
no idea what this was supposed to mean
