### ISSUE TITLE
I would like to know if it can obfuscate all Lua files within a folder?

### ISSUE THREAD

**Issue by buxiaomao6** [zeusssz/hercules-obfuscator#8]
I would like to know if it can obfuscate all Lua files within a folder?

**Comment by zeusssz** [comment]
you do need to obfuscate one by one for now, but a gui is in progress for bulk obfuscation. this is a good feature though, you may mark this as a feature request if you want

**Comment by zeusssz** [comment]
@buxiaomao6 added this
